const faceis = [
    "objetos",
    "comidas",
    "Animais",
    "filmes",
    "personagens",
    "cantor/cantora/banda",
    "frutas",
    "objetos escolares",
    "comidas de café da manhã",
    "coisas azuis",
    "coisas redondas",
    "adjetivos",
    "filmes da disney",
    "monstros e criaturas míticas",
    "nomes de bichos de estimação",
    "neste recinto",
    "profissões e ocupações",
    "vestuário",
    "partes do corpo humano",
    "nomes femininos",
    "nomes masculinos",
    "países, cidades e estados",
    "jogos",
    "coisas vermelhas",
    "comidas de padaria",
    "coisas de jardim",
    "objetos de banheiro",
    "sobremesas",
    "heróis/heroínas",
    "coisas macias",
    "eletrônicos",
    "brinquedos",
    "vegetais",
    "coisas para usar na cabeça",
    "objetos de quarto",
    "material de escritório",
    "cores",
    "desenhos animados",
    "seriados",
    "insetos",
    "coisas do museu",
    "ervas e temperos",
    "hábitos ruins",
    "na floresta",
    "sabores de sorvete",
    "no oceano",
    "bebidas",
    "produtos de limpeza",
    "comida porcaria (junkie food)",
    "coisas assustadoras",
    "cosméticos",
];

  const dificeis = [
      "celebridades",
      "coisas de um casamento",
      "objetos com botões",
      "equipamentos esportivos",
      "reptéis e anfíbios",
      "metais preciosos e gemas",
      "palavras com cinco letras",
      "esportes olímpicos",
      "ator/atriz",
      "coisas úmidas/molhadas",
      "livros",
      "instrumentos musicais",
      "armas",
      "hobbies",
      "flores e plantas",
      "carros",
      "partes do carro",
      "figuras históricas",
      "políticos",
      "objetos de consultório médico",
      "coisas circenses",
      "coisas grudentas",
      "sabores de pizza",
      "tipos de queijo",
      "motivos para uma comemoração/festa",
      "termos de computação",
      "carnes",
      "Áreas da ciência",
  ]